//
//  ShowInfoViewController.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 3/03/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowInfoDisplayLogic: class {
    func displayAttributedString(viewModel: ShowInfo.Info.ViewModel)
}



class ShowInfoViewController: UIViewController, ShowInfoDisplayLogic {
    var interactor: ShowInfoBusinessLogic?
    
    @IBOutlet weak var textView: UITextView!
    

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = ShowInfoInteractor()
        let presenter = ShowInfoPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }


    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        fetchAttributedString()
    }

    // MARK: VIP
    
    func fetchAttributedString() {
        let request = ShowInfo.Info.Request() 
        interactor?.fetchAttributedString(request: request)
    }
    
    
    func displayAttributedString(viewModel: ShowInfo.Info.ViewModel) {
        textView?.attributedText = viewModel.attString
    }


}
