//
//  ShowInfoModels.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 3/03/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowInfo {
  // MARK: Use cases
  
    enum Info {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
            var attString: NSAttributedString?
        }
    }
}
