//
//  ShowProfileRouter.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 8/02/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowProfileRoutingLogic {
    func routeToShowProfileItem(segue: UIStoryboardSegue?)
    func returnFromEditing()
    func returnAfterSelectingLink()
}

protocol ShowProfileDataPassing {
    var dataStore: ShowProfileDataStore? { get }
}

class ShowProfileRouter: NSObject, ShowProfileRoutingLogic, ShowProfileDataPassing {
    weak var viewController: ShowProfileViewController?
    var dataStore: ShowProfileDataStore?
  
  // MARK: Routing
  
  func routeToShowProfileItem(segue: UIStoryboardSegue?) {
    if let segue = segue {
      let destinationVC = (segue.destination as! UINavigationController).viewControllers[0] as! EditProfileViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    }
  }

    
    func returnFromEditing() {
        viewController!.itemWasEdited()
    }
  
    func returnAfterSelectingLink() {
        viewController!.linkWasSelected()
    }
    
  // MARK: Passing data
  
  func passDataToSomewhere(source: ShowProfileDataStore, destination: inout EditProfileDataStore) {
    destination.selectedItem = source.selectedItem
    destination.context = source.context
    destination.storeTriples = source.storeTriples
    destination.webid = source.webid
  }
}
