//
//  ShowProfileModels.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 8/02/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowProfile {
    
    // MARK: Use cases
    
    enum Profile {
        struct Request {
            var webid: String?
        }
        struct Response {
            var triples: [Triple]?
        }
        struct ViewModel {
            var sections: [Section]?
        }
    }
}

struct Section {
    var sectionIndex: Int?
    var isUnfolded = true
    var sectionName: String?
    var sectionData = [(String, String, Int)]()  // Predicate, object and associated triple index
    init(name: String) {
        self.sectionName = name
    }
}


struct Triple {
    var index: Int?
    var subject: (String, String)
    var predicate: (String, String)
    var object: (String, String)
    var why: String
    init(index: Int?, subject: (String, String), predicate: (String, String), object: (String, String)) {
        self.index = index
        self.subject = subject
        self.predicate = predicate
        self.object = object
        self.why = ""
    }
}
