//
//  EditProfileViewController.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 11/02/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileDisplayLogic: class {
    func displaySomething(viewModel: EditProfile.EditTriple.ViewModel)
}



class EditProfileViewController: UIViewController, EditProfileDisplayLogic {
    var interactor: EditProfileBusinessLogic?
    var router: (NSObjectProtocol & EditProfileRoutingLogic & EditProfileDataPassing)?

    
    @IBOutlet weak var subjectLabel: UILabel!
    @IBOutlet weak var predicateLabel: UILabel!
    @IBOutlet weak var objectLabel: UILabel!
    
    @IBOutlet weak var objectTextField: UITextField!
    
    
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = EditProfileInteractor()
        let presenter = EditProfilePresenter()
        let router = EditProfileRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
    override func viewDidAppear(_ animated: Bool) {
        let triple  = getSelectedItem()
        subjectLabel.text = triple.subject.0
        predicateLabel.text = triple.predicate.0
        objectLabel.text = triple.object.0
        
        objectTextField.text = triple.object.0
    }
    
    // MARK: - User actions
    
    @IBAction func saveButtonPressed(_ sender: Any) {
        saveTriple()
    }
    

    // MARK: - VIP

    func saveTriple() {
        let selectedItem = getSelectedItem()
        let subject = (subjectLabel.text!, selectedItem.subject.1)
        let predicate = (predicateLabel.text!, selectedItem.predicate.1)
        let object = (objectTextField.text!, selectedItem.object.1)
        let triple = Triple(index: selectedItem.index, subject: subject, predicate: predicate, object: object)
        let request = EditProfile.EditTriple.Request(triple: triple)
        interactor?.saveTriple(request: request, callback: { message in
            if message == "unauthorized" {
                self.router!.navigateToAuthentication()
            }
            else if message == "success" {
                let splitViewController = UIApplication.shared.delegate?.window!!.rootViewController as! UISplitViewController
                if splitViewController.isCollapsed {
                    self.router!.showMasterViewController()
                }
            }
        })
    }


    func displaySomething(viewModel: EditProfile.EditTriple.ViewModel) {
    //nameTextField.text = viewModel.name
    }
    
    // MARK: - Datastore
    
    func getSelectedItem()->Triple {
        return interactor!.getSelectedItem()
    }
}
