//
//  EditProfilePresenter.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 11/02/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfilePresentationLogic {
    func presentSomething(response: EditProfile.EditTriple.Response)
}



class EditProfilePresenter: EditProfilePresentationLogic {
    weak var viewController: EditProfileDisplayLogic?

    // MARK: Do something

    func presentSomething(response: EditProfile.EditTriple.Response) {
        let viewModel = EditProfile.EditTriple.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
