//
//  DisplayRecentsPopUpPresenter.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 24/02/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayRecentsPopupPresentationLogic {
    func presentRecents(response: DisplayRecentsPopup.Recents.Response)
}

class DisplayRecentsPopupPresenter: DisplayRecentsPopupPresentationLogic {
    weak var viewController: DisplayRecentsPopupDisplayLogic?
    
    // MARK: - VIP
    
    func presentRecents(response: DisplayRecentsPopup.Recents.Response) {
        let viewModel = DisplayRecentsPopup.Recents.ViewModel(recentsArray: response.recentsArray)
        viewController?.displayRecents(viewModel: viewModel)
    }
}
