//
//  DisplayRecentsPopUpInteractor.swift
//  Profile editor
//
//  Created by Warwick McNaughton on 24/02/19.
//  Copyright (c) 2019 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayRecentsPopupBusinessLogic {
    func fetchRecents(request: DisplayRecentsPopup.Recents.Request)
}

protocol DisplayRecentsPopupDataStore {
    //var name: String { get set }
}

class DisplayRecentsPopupInteractor: DisplayRecentsPopupBusinessLogic, DisplayRecentsPopupDataStore {
    var presenter: DisplayRecentsPopupPresentationLogic?
    
    
    // MARK: - VIP
    
    func fetchRecents(request: DisplayRecentsPopup.Recents.Request) {
        var recentsArray = [String]()
        let defaults = UserDefaults.standard
        if let recentsData = defaults.data(forKey: "Recents") {
            recentsArray = try! JSONDecoder().decode([String].self, from: recentsData)
        }
        
        let response = DisplayRecentsPopup.Recents.Response(recentsArray: recentsArray)
        presenter?.presentRecents(response: response)
    }
}
